# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a9799ca1c31fd92ef4155f32798651dd780f665aaea3e9950e3c77a9d92f0b747f14bd84d22078ad19991dbab63c892848ce85619a606d447d23f378d62360af

test:
  secret_key_base: 8311a11d71a098e4dd39179ed1afd4e70532293ca53f30a30bf216e7cda3b20880c731b2a0453e4642a7d058d3332776647701e800d9687b9c14f357a49fb0c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
